### ISSUE TITLE
4.26.1 - Failed to compile "global shader TVolumetricFogLightScatteringCS "

### ISSUE THREAD

**Issue by derskyy** [RDTG/UnrealEngineRetroreflections#2]
![grafik](https://user-images.githubusercontent.com/61698073/135058214-0bab88a8-8eff-49c0-b8e7-389287645ea3.png)

Hi, idk. this is a problem for developing a game but i get ^ this error -- when i add "r.ShaderDevelopmentMode=1" to my StartUp ConsoleVars, i get this error:

![grafik](https://user-images.githubusercontent.com/61698073/135058609-d1a7327b-fded-47f7-a094-bef509b2bbd4.png)

(I replaced the "ShadingModels.ush" as you mentioned on your git page)

**Comment by RDTG** [comment]
My bad, I completely forgot to add that function. Grab the latest and it should work now :)
