### ISSUE TITLE
Crashing when using with UE5

### ISSUE THREAD

**Issue by youngbin-song** [RDTG/UnrealEngineRetroreflections#3]
It seems like when I replace the ShadingModels.ush into the UE5 folder, it causes a crash upon reaching the end of shader compiling.

**Comment by RDTG** [comment]
I will be pushing a new version shortly that is compatible with Unreal Engine 5 Preview 1. The version on here was only tested with Early Access 1.

**Comment by youngbin-song** [comment]
Good to know! Thanks for doing this and I'm looking forward to it.

Cheers!

**Comment by RDTG** [comment]
Update pushed. Should now work fine with Unreal Engine 5.0.0 Preview 2 and you should also be able to package a project using it with no issues. Use Default Lit now instead of the Retroreflective shading model.
